language: lisp

branches:
  only:
    - master

env:
  matrix:
    - LISP=sbcl
    - LISP=ecl

install:
  - curl https://gist.githubusercontent.com/mmontone/87a4a3d361fa4ebfba72/raw/f0dcd7b66cd5a817fdd7914f76b1d08c35175159/install.sh | bash

script:
  - cl-launch -i "(ql:quickload :rest-server-tests)(rest-server-tests:debug-tests)"
