language: lisp

branches:
  only:
    - master

env:
  matrix:
    - LISP=sbcl
    - LISP=abcl

install:
  - curl https://gist.githubusercontent.com/mmontone/87a4a3d361fa4ebfba72/raw/43458e7280e5ddaf844c86b8fd9a8562e8b2f3ca/install.sh | bash

before_script:

script:
  - cl-launch -i "(setf *readtable* (copy-readtable nil))(ql:quickload :rest-server-tests)(rest-server-tests:debug-tests)"
